FROM node:22.14.0-alpine
WORKDIR /app

COPY package.json package-lock.json ./
COPY .npmrc ./.npmrc
COPY apps/renderer/package.json apps/renderer/package.json

RUN --mount=type=cache,target=/root/.npm \
    npm ci --workspace apps/renderer --include-workspace-root=false --prefer-offline --no-audit --progress=false
