import { cn } from "@/lib/utils";

export const artifactEditorContentClassName = cn(
  "artifact-prosemirror-editor size-full max-w-none focus:outline-none",
  "[&_.ProseMirror]:size-full [&_.ProseMirror]:outline-none [&_.ProseMirror]:break-words",
  "[&_.ProseMirror>*:first-child]:mt-0 [&_.ProseMirror>*:last-child]:mb-0 [&_.ProseMirror_li>p]:m-0 [&_.ProseMirror_li>p]:inline",
  "[&_.ProseMirror]:text-base [&_.ProseMirror]:leading-[1.65]",
  "[&_.ProseMirror_h1]:mt-0 [&_.ProseMirror_h1]:mb-4 [&_.ProseMirror_h1]:font-bold [&_.ProseMirror_h1]:leading-tight",
  "[&_.ProseMirror_>h1:first-child]:text-[30px]",
  "[&_.ProseMirror_h1:not(:first-child)]:text-[24px]",
  "[&_.ProseMirror_h2]:mt-5 [&_.ProseMirror_h2]:mb-4 [&_.ProseMirror_h2]:text-[20px] [&_.ProseMirror_h2]:font-semibold [&_.ProseMirror_h2]:leading-tight",
  "[&_.ProseMirror_h3]:mt-5 [&_.ProseMirror_h3]:mb-4 [&_.ProseMirror_h3]:text-[18px] [&_.ProseMirror_h3]:font-semibold",
  "[&_.ProseMirror_h4]:mt-5 [&_.ProseMirror_h4]:mb-4 [&_.ProseMirror_h4]:text-[16px] [&_.ProseMirror_h4]:font-semibold",
  "[&_.ProseMirror_p]:mt-0 [&_.ProseMirror_p]:mb-3",
  "[&_.ProseMirror_ul]:mt-0 [&_.ProseMirror_ul]:mb-3 [&_.ProseMirror_ul]:list-disc [&_.ProseMirror_ul]:pl-6",
  "[&_.ProseMirror_ol]:mt-0 [&_.ProseMirror_ol]:mb-3 [&_.ProseMirror_ol]:list-decimal [&_.ProseMirror_ol]:pl-6",
  "[&_.ProseMirror_blockquote]:my-4 [&_.ProseMirror_blockquote]:border-l-4 [&_.ProseMirror_blockquote]:border-border [&_.ProseMirror_blockquote]:pl-4 [&_.ProseMirror_blockquote]:text-muted-foreground",
  "[&_.ProseMirror_.tableWrapper]:my-5 [&_.ProseMirror_.tableWrapper]:overflow-x-auto [&_.ProseMirror_.tableWrapper]:overflow-y-hidden",
  "[&_.ProseMirror_table]:w-full [&_.ProseMirror_table]:border-collapse [&_.ProseMirror_table]:table-fixed [&_.ProseMirror_table]:text-sm",
  "[&_.ProseMirror_th]:relative [&_.ProseMirror_th]:border [&_.ProseMirror_th]:border-border [&_.ProseMirror_th]:bg-muted/60 [&_.ProseMirror_th]:px-3 [&_.ProseMirror_th]:py-2 [&_.ProseMirror_th]:text-left [&_.ProseMirror_th]:font-semibold [&_.ProseMirror_th]:align-top",
  "[&_.ProseMirror_td]:relative [&_.ProseMirror_td]:border [&_.ProseMirror_td]:border-border [&_.ProseMirror_td]:px-3 [&_.ProseMirror_td]:py-2 [&_.ProseMirror_td]:align-top",
  "[&_.ProseMirror_th>p]:m-0 [&_.ProseMirror_td>p]:m-0",
  "[&_.ProseMirror_.selectedCell]:bg-primary/10",
  "[&_.ProseMirror_.column-resize-handle]:pointer-events-none [&_.ProseMirror_.column-resize-handle]:absolute [&_.ProseMirror_.column-resize-handle]:top-0 [&_.ProseMirror_.column-resize-handle]:right-[-1px] [&_.ProseMirror_.column-resize-handle]:bottom-0 [&_.ProseMirror_.column-resize-handle]:z-10 [&_.ProseMirror_.column-resize-handle]:w-0.5 [&_.ProseMirror_.column-resize-handle]:bg-primary/50",
  "[&_.ProseMirror.resize-cursor]:cursor-col-resize",
  "[&_.ProseMirror_img]:mt-6 [&_.ProseMirror_img]:mb-6 [&_.ProseMirror_img]:mx-auto [&_.ProseMirror_img]:block [&_.ProseMirror_img]:h-auto [&_.ProseMirror_img]:max-w-full [&_.ProseMirror_img]:rounded-xl [&_.ProseMirror_img]:cursor-pointer [&_.ProseMirror_img]:transition-shadow",
  "[&_.ProseMirror_img.ProseMirror-selectednode]:ring-2 [&_.ProseMirror_img.ProseMirror-selectednode]:ring-primary/60 [&_.ProseMirror_img.ProseMirror-selectednode]:ring-offset-2 [&_.ProseMirror_img.ProseMirror-selectednode]:ring-offset-background",
  "[&_.ProseMirror_p:has(>br.ProseMirror-trailingBreak):has(+img)]:hidden",
  "[&_.ProseMirror_img+p:has(>br.ProseMirror-trailingBreak)]:hidden",
  // Placeholder: visible text but does not occupy layout space.
  "[&_.ProseMirror_p.is-empty::before]:pointer-events-none [&_.ProseMirror_p.is-empty::before]:float-left [&_.ProseMirror_p.is-empty::before]:h-0 [&_.ProseMirror_p.is-empty::before]:text-muted-foreground/70 [&_.ProseMirror_p.is-empty::before]:content-[attr(data-placeholder)]",
  "[&_.ProseMirror_h1.is-empty::before]:pointer-events-none [&_.ProseMirror_h1.is-empty::before]:float-left [&_.ProseMirror_h1.is-empty::before]:h-0 [&_.ProseMirror_h1.is-empty::before]:text-muted-foreground/70 [&_.ProseMirror_h1.is-empty::before]:content-[attr(data-placeholder)]",
  "[&_.ProseMirror_h2.is-empty::before]:pointer-events-none [&_.ProseMirror_h2.is-empty::before]:float-left [&_.ProseMirror_h2.is-empty::before]:h-0 [&_.ProseMirror_h2.is-empty::before]:text-muted-foreground/70 [&_.ProseMirror_h2.is-empty::before]:content-[attr(data-placeholder)]",
  "[&_.ProseMirror_h3.is-empty::before]:pointer-events-none [&_.ProseMirror_h3.is-empty::before]:float-left [&_.ProseMirror_h3.is-empty::before]:h-0 [&_.ProseMirror_h3.is-empty::before]:text-muted-foreground/70 [&_.ProseMirror_h3.is-empty::before]:content-[attr(data-placeholder)]",
  "[&_.ProseMirror_h4.is-empty::before]:pointer-events-none [&_.ProseMirror_h4.is-empty::before]:float-left [&_.ProseMirror_h4.is-empty::before]:h-0 [&_.ProseMirror_h4.is-empty::before]:text-muted-foreground/70 [&_.ProseMirror_h4.is-empty::before]:content-[attr(data-placeholder)]",
  "[&_.ProseMirror_a]:cursor-pointer [&_.ProseMirror_a]:text-primary [&_.ProseMirror_a]:underline [&_.ProseMirror_a]:decoration-primary/30 [&_.ProseMirror_a]:underline-offset-2",
);
