import type { PublishPlatformMeta } from "../types";

export const CN_PUBLISH_PLATFORM_CATALOG: PublishPlatformMeta[] = [
  {
    id: "toutiao",
    label: "头条号",
    pickerLabel: "今日头条",
    logoPath: "/platform-logos/jin-ri-tou-tiao.png",
    pickerVisible: true,
    optionOrder: [
      "cover_mode",
      "enable_ad",
      "first_publish",
      "work_statement",
      "info_source",
      "source_author_uid",
    ],
  },
  {
    id: "rednote",
    label: "小红书",
    pickerLabel: "小红书",
    logoPath: "/platform-logos/xiao-hong-shu.png",
    pickerVisible: true,
    optionOrder: ["privacy", "original", "note_copyable"],
  },
  {
    id: "wechat_mp",
    label: "公众号",
    pickerLabel: "微信公众号",
    logoPath: "/platform-logos/wei-xin-gong-zhong-hao.png",
    pickerVisible: true,
    optionOrder: ["claim_source", "enable_comment", "platform_recommend"],
  },
  {
    id: "zhihu",
    label: "知乎",
    pickerLabel: "知乎",
    logoPath: "/platform-logos/zhihu.png",
    pickerVisible: true,
    optionOrder: ["cover_image"],
  },
  {
    id: "csdn",
    label: "CSDN",
    pickerLabel: "CSDN",
    logoPath: "/platform-logos/CSDN.png",
    pickerVisible: true,
    optionOrder: [
      "article_id",
      "description",
      "tags",
      "categories",
      "cover_image",
      "article_type",
      "read_type",
      "creation_statement",
      "scheduled_at",
      "scheduled_time",
    ],
  },
  {
    id: "baijiahao",
    label: "百家号",
    pickerLabel: "百家号",
    logoPath: "/platform-logos/bai-jia-hao.png",
    pickerVisible: true,
    optionOrder: [
      "abstract",
      "cover_layout",
      "cover_images",
      "feed_cat",
      "activity_list",
      "declare_aigc",
      "auto_tts",
      "creative_method",
      "original_announce",
      "event_spec",
      "settings",
    ],
  },
  {
    id: "douyin",
    label: "抖音",
    pickerLabel: "抖音",
    logoPath: "/platform-logos/dou-yin.png",
    pickerVisible: false,
  },
  {
    id: "wechat_channels",
    label: "视频号",
    pickerLabel: "微信视频号",
    logoPath: "/platform-logos/wei-xin-shi-pin-hao.png",
    pickerVisible: false,
  },
];
